In [19]:
import pandas as pd

In [22]:
nk=pd.read_csv(r'C:\Users\USER\Downloads\insurance (4).csv ' )

In [3]:
nk.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
nk.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

In [5]:
nk.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [18]:
#what is the average value of bmi grouped by the region ?

In [7]:
nk.groupby('region')['bmi'].mean()

region
northeast    29.173503
northwest    29.199785
southeast    33.355989
southwest    30.596615
Name: bmi, dtype: float64

In [8]:
#it is found that for regions the highest average of bmi is 33.35 in southest

In [9]:
#what is the number of smokers grouped by sex of the smoker?

In [10]:
nk.groupby('sex')['smoker'].count()

sex
female    662
male      676
Name: smoker, dtype: int64

In [11]:
#there're more smoker male

In [12]:
#what is above most common number of children that people have

In [13]:
chil_count= nk['children'].value_counts()
print(chil_count) 
bigs_count= nk['children'].value_counts().idxmax()
print("most people only have ")

print(bigs_count )

children
0    574
1    324
2    240
3    157
4     25
5     18
Name: count, dtype: int64
most people only have
0

In [14]:
#most people only have 0 children & less people have 5 children

In [15]:
#what is file's number of smoker people that are  older than 40 ?

In [16]:
ntrs = nk [ (nk['smoker'] == 'yes')  & (nk['age']>=48) ]
print(ntrs.shape[0])

77

#there're 70 smokers are older than 48 years

In [17]:
#checking if it's clean 
nk.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [26]:
#perfect there's 0 null values 
nk.duplicated().sum()

np.int64(1)

In [27]:
nk.str.strip().str.lower()

AttributeError: 'DataFrame' object has no attribute 'str'

In [31]:
nk.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

In [32]:
#this is clean dataset
#what factors are associated with higher insurance values of charges? 
print('This analysis investigates whether age, BMI, smoking status, sex, number of children, and region are associated with higher insurance charges.') 
nk['charges'].describe()

count     1338.000000
mean     13270.422265
std      12110.011237
min       1121.873900
25%       4740.287150
50%       9382.033000
75%      16639.912515
max      63770.428010
Name: charges, dtype: float64

In [34]:
nk['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [ ]:
print(' The dataset is fairly balanced across regions.')

In [35]:
nk['smoker'].value_counts()

smoker
no     1064
yes     274
Name: count, dtype: int64

In [ ]:
print(' Most individuals are non-smokers.')

In [36]:
nk.groupby('children')['charges'].mean()

children
0    12365.975602
1    12731.171832
2    15073.563734
3    15355.318367
4    13850.656311
5     8786.035247
Name: charges, dtype: float64

In [ ]:
#nothing is real affecting

In [37]:
nk.groupby('sex')['charges'].mean()

sex
female    12569.578844
male      13956.751178
Name: charges, dtype: float64

In [ ]:
#girl gets fewer charges

In [38]:
nk.groupby('region')['charges'].mean()

region
northeast    13406.384516
northwest    12417.575374
southeast    14735.411438
southwest    12346.937377
Name: charges, dtype: float64

In [ ]:
#region slightly affecting charges, this mean regions affect average rate of charges according to each area and here southest is the highest and southwest is lowest and maybe being in east affects charges since eastern south and north are higher than western ones

In [40]:
nk.groupby

<bound method DataFrame.groupby of       age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]>

In [41]:
nk.groupby('age')['charges'].mean()

age
18     7086.217556
19     9747.909335
20    10159.697736
21     4730.464330
22    10012.932802
23    12419.820040
24    10648.015962
25     9838.365311
26     6133.825309
27    12184.701721
28     9069.187564
29    10430.158727
30    12719.110358
31    10196.980573
32     9220.300291
33    12351.532987
34    11613.528121
35    11307.182031
36    12204.476138
37    18019.911877
38     8102.733674
39    11778.242945
40    11772.251310
41     9653.745650
42    13061.038669
43    19267.278653
44    15859.396587
45    14830.199856
46    14342.590639
47    17653.999593
48    14632.500445
49    12696.006264
50    15663.003301
51    15682.255867
52    18256.269719
53    16020.930755
54    18758.546475
55    16164.545488
56    15025.515837
57    16447.185250
58    13878.928112
59    18895.869532
60    21979.418507
61    22024.457609
62    19163.856573
63    19884.998461
64    23275.530837
Name: charges, dtype: float64

In [42]:
#no clearer?
nk.groupby('smoker')['charges'].mean()

smoker
no      8434.268298
yes    32050.231832
Name: charges, dtype: float64

In [43]:
# 32050 $ for smokers and only 8434 $ for non-smokersr charges ar
nk.groupby('bmi')['charges'].mean()

bmi
15.960     1694.796400
16.815     4904.000350
17.195    14455.644050
17.290     7813.353433
17.385     2775.192150
              ...
48.070     9432.925300
49.060    11381.325400
50.380     2438.055200
52.580    44501.398200
53.130     1163.462700
Name: charges, Length: 548, dtype: float64

In [46]:
nk[['bmi','age','charges']].corr()

              bmi       age   charges
bmi      1.000000  0.109272  0.198341
age      0.109272  1.000000  0.299008
charges  0.198341  0.299008  1.000000

In [ ]:
#this correlation is showing  positive correlation between age and charges (r=0.3) means age affect charges where high charges are tend to be for older people 
#this correlation is showing positive relation between bmi and charges (r=0.2) which means that higher body mass index is associated with higher insurance charges
#factors that can affect insurance charges are age,sexs,smoking, BMI, regions while children are not showing strong relationship   
 # Key Findings

# Smoking status has the strongest relationship with insurance charges. Smokers pay an average of about $32,050, compared with about $8,434 for non-smokers.

# Age is positively correlated with insurance charges (r ≈ 0.30), indicating that older individuals tend to have higher medical costs.

# BMI is also positively correlated with insurance charges (r ≈ 0.20), suggesting that people with higher body mass index generally face higher insurance charges.